### ISSUE TITLE
Failed to load dynamic library '/data/data/institute.flutter.webauthnexample/lib/libsqlite3.so'

### ISSUE THREAD

**Issue by thomastthai** [flutter-institute/webauthn#3]
System setup: VSCode on Windows 11, Android device plugged in via USB.

The error below shows up when entering a username and clicking on `Register` in the example app:

> E/flutter (19034): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqfliteFfiException(sqlite_error: 14, , open_failed: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)}) DatabaseException(open_failed: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21))

It looks like it's trying to open the database but can't or have [read/write permission issues](https://stackoverflow.com/questions/71750668/flutter-windows-c-drive-permission-problem-using-path-provider-and-sqflite).

![image](https://user-images.githubusercontent.com/16532581/214015779-3971f16f-a5ca-41dc-b7c4-f47e72300098.png)

**Comment by thomastthai** [comment]
Commenting out line #20:

`  //databaseFactory = databaseFactoryFfi;`

allowed the example app to perform as intended with an Android device attached via USB.

Why is that the case?

**Comment by killermonk** [comment]
Hey @thomastthai, the sqfliteFfi is the driver required to get the app to work on desktop OS's (https://pub.dev/packages/sqflite_common_ffi). This factory needs to be left out if the project is running on a mobile device.

It looks like I didn't properly review all the changes in the MR that merged this code in, because we should only be changing the databaseFactory if the platform is Desktop. Would you be wiling to submit an MR that changes the main.dart's main function to be as follows?

```
  if (Platform.isWindows || Platform.isLinux) {
    // Initialize FFI
    sqfliteFfiInit();
    
    // Change the default factory. On iOS/Android, if not using `sqlite_flutter_lib` you can forget
    // this step, it will use the sqlite version available on the system.
    databaseFactory = databaseFactoryFfi;
  }
```

All the FFI stuff should be inside that if statement.

**Comment by thomastthai** [comment]
@killermonk, thanks for clarifying. Your merge request has been submitted.

**Comment by killermonk** [comment]
MR is merged, and I'll be publishing a new release with the updated example shortly. Thank you!
